# Generated by Django 5.1.7 on 2026-04-18 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(blank=True, null=True, upload_to='bosses/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BossSpawnConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monsters_per_server', models.PositiveSmallIntegerField(default=1)),
                ('server_count', models.PositiveSmallIntegerField(default=1)),
                ('respawn_min_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('respawn_max_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spawn_configs', to='tracker.boss')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spawn_configs', to='tracker.map')),
            ],
            options={
                'ordering': ['boss__name', 'map__name'],
                'unique_together': {('boss', 'map')},
            },
        ),
        migrations.CreateModel(
            name='SpawnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_number', models.PositiveSmallIntegerField()),
                ('monster_index', models.PositiveSmallIntegerField(default=1)),
                ('last_death', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tracker.bossspawnconfig')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawn_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['config__boss__name', 'server_number', 'monster_index'],
                'unique_together': {('config', 'server_number', 'monster_index')},
            },
        ),
    ]
