# Generated by Django 5.1.7 on 2026-04-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='boss',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
