# Generated by Django 5.1.7 on 2026-04-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_add_display_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='image',
        ),
        migrations.AddField(
            model_name='boss',
            name='gif_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
